title: Casey's Stucco
baseurl: ""
url: "http://www.caseysstucco.com"
markdown: kramdown

description: Casey's Stucco is a local Livermore, California Stucco Repair Expert with over 30 years of experience in the industry.

exclude:
  - Gemfile
  - Gemfile.lock
  - [vendor]
  - vendor

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Casey's Stucco
  location: Livermore, California

gems:
  - jekyll-sitemap
